// src/menuData.js
export const MASTER_MENU_DATASET = [
  // 1. VEG SOUPS
  { id: 'soup-1', name: 'TOMATO SOUP', category: 'VEG SOUPS', price: 100, description: 'Classic tomato soup.' },
  { id: 'soup-2', name: 'SWEET CORN SOUP', category: 'VEG SOUPS', price: 100, description: 'Comforting sweet corn soup.' },
  { id: 'soup-3', name: 'VEG CORN SOUP', category: 'VEG SOUPS', price: 120, description: 'Hearty mixed veg and corn soup.' },
  { id: 'soup-4', name: 'VEG HOT \'N\' SOUR SOUP', category: 'VEG SOUPS', price: 120, description: 'Spicy and tangy vegetable soup.' },
  
  // 2. VEG STARTERS
  { id: 'starter-1', name: 'VEG SPRING ROLL', category: 'VEG STARTERS', price: 250, description: 'Crispy deep-fried rolls packed with seasoned minced vegetables.' },
  { id: 'starter-2', name: 'PANEER 65', category: 'VEG STARTERS', price: 240, description: 'Spicy cottage cheese cubes tossed with curry leaves and chilis.' },
  { id: 'starter-3', name: 'CHILLY PANEER', category: 'VEG STARTERS', price: 240, description: 'Wok-tossed paneer cubes with bell peppers and spicy dark soy sauce.' },
  { id: 'starter-4', name: 'PANEER MANCHURIA', category: 'VEG STARTERS', price: 240, description: 'Fried paneer dumplings tossed in a classic tangy Manchurian gravy.' },
  { id: 'starter-5', name: 'MUSHROOM 65', category: 'VEG STARTERS', price: 240, description: 'Crispy fried button mushrooms coated in house-special spice blends.' },
  { id: 'starter-6', name: 'MUSHROOM DRY ROAST', category: 'VEG STARTERS', price: 240, description: 'Button mushrooms slow-roasted with cracked black pepper.' },
  { id: 'starter-7', name: 'CHILLY MUSHROOM', category: 'VEG STARTERS', price: 240, description: 'Tender mushrooms wok-fried with fresh green chilis and garlic.' },
  { id: 'starter-8', name: 'CHILLY BABY CORN', category: 'VEG STARTERS', price: 240, description: 'Crispy baby corn spears tossed in a sweet, spicy chili glaze.' },
  { id: 'starter-9', name: 'CRISPY BABY CORN', category: 'VEG STARTERS', price: 240, description: 'Golden, crunch-fried baby corn lightly dusted with salt and pepper.' },
  { id: 'starter-10', name: 'GOBI MANCHURIA', category: 'VEG STARTERS', price: 240, description: 'Crispy cauliflower florets tossed in ginger-garlic Manchurian sauce.' },
  { id: 'starter-11', name: 'VEG MANCHURIA', category: 'VEG STARTERS', price: 200, description: 'Mixed vegetable balls fried and glazed in soy-garlic reduction.' },
  { id: 'starter-12', name: 'VEG 99', category: 'VEG STARTERS', price: 220, description: 'Crispy vegetable shreds tossed in chef\'s secret red spicy glaze.' },
  { id: 'starter-13', name: 'CRISPY VEG', category: 'VEG STARTERS', price: 180, description: 'Assorted seasonal garden vegetables batter-fried to a delicate crisp.' },
  { id: 'starter-14', name: 'PANEER MAJESTIC', category: 'VEG STARTERS', price: 250, description: 'Stripped paneer glazed in a rich yogurt, mint, and garlic sauce.' },
  { id: 'starter-15', name: 'PANEER 555', category: 'VEG STARTERS', price: 250, description: 'Premium layered paneer strips tossed with cashews and red spice strings.' },

  // 3. VEG BRIYANI
  { id: 'briyani-1', name: 'VEG BRIYANI', category: 'VEG BRIYANI', price: 160, description: 'Aromatic basmati rice cooked with garden vegetables and spices.' },
  { id: 'briyani-2', name: 'SP VEG BRIYANI', category: 'VEG BRIYANI', price: 220, description: 'Rich vegetable biryani layered with extra premium dry fruits and spices.' },
  { id: 'briyani-3', name: 'PANEER BRIYANI', category: 'VEG BRIYANI', price: 200, description: 'Delicious basmati rice slow cooked with soft, spiced marinated paneer cubes.' },
  { id: 'briyani-4', name: 'SP PANEER BRIYANI', category: 'VEG BRIYANI', price: 260, description: 'Richly loaded specialty paneer biryani featuring roasted cashews.' },
  { id: 'briyani-5', name: 'MUSHROOM BRIYANI', category: 'VEG BRIYANI', price: 200, description: 'Fragrant biryani rice layered with slow-cooked masala button mushrooms.' },
  { id: 'briyani-6', name: 'SP MUSHROOM BRIYANI', category: 'VEG BRIYANI', price: 260, description: 'Elevated mushroom biryani cooked with chef\'s secret spice blend.' },
  { id: 'briyani-7', name: 'MUSHROOM ROSE BRIYANI', category: 'VEG BRIYANI', price: 280, description: 'Unique premium biryani infused with aromatic rose extracts.' },
  { id: 'briyani-8', name: 'PANEER ROSE BRIYANI', category: 'VEG BRIYANI', price: 280, description: 'Aromatic rose petal extracts layered with soft spiced paneer blocks.' },
  { id: 'briyani-9', name: 'BABY CORN BRIYANI', category: 'VEG BRIYANI', price: 200, description: 'Crisp baby corn segments tossed in authentic dum biryani masala and rice.' },
  { id: 'briyani-10', name: 'SP BABY CORN BRIYANI', category: 'VEG BRIYANI', price: 260, description: 'Special rich baby corn biryani enhanced with whole spice aromatics.' },
  { id: 'briyani-11', name: 'GOBI BIRYANI', category: 'VEG BRIYANI', price: 200, description: 'Crispy cauliflower florets tossed in special biryani gravy and dum-cooked.' },

  // 4. VEG RICE & NOODELS
  { id: 'rice-1', name: 'VEG FRIED RICE', category: 'VEG RICE & NOODELS', price: 160, description: 'Classic wok-tossed basmati rice with finely chopped garden vegetables.' },
  { id: 'rice-2', name: 'SP VEG FRIED RICE', category: 'VEG RICE & NOODELS', price: 240, description: 'Chef\'s special aromatic vegetable fried rice enriched with premium toppings.' },
  { id: 'rice-3', name: 'PANEER FRIED RICE', category: 'VEG RICE & NOODELS', price: 240, description: 'Flavorful pan-fried rice tossed with golden-brown spiced paneer cubes.' },
  { id: 'rice-4', name: 'SP PANEER FRIED RICE', category: 'VEG RICE & NOODELS', price: 240, description: 'Premium paneer fried rice prepared with fine aromatic spice layers and roasted cashews.' },
  { id: 'rice-5', name: 'MUSHROOM FRIED RICE', category: 'VEG RICE & NOODELS', price: 240, description: 'Savory stir-fried rice loaded with fresh button mushrooms.' },
  { id: 'rice-6', name: 'SP MUSHROOM FRIED RICE', category: 'VEG RICE & NOODELS', price: 280, description: 'Special rich mushroom fried rice tossed in a deep aromatic blend of spices.' },
  { id: 'rice-7', name: 'VEG SCHEZWAN FRIED RICE', category: 'VEG RICE & NOODELS', price: 240, description: 'Fiery wok-tossed rice running with spicy, authentic house-made Schezwan chili paste.' },
  { id: 'rice-8', name: 'JEERA FRIED RICE', category: 'VEG RICE & NOODELS', price: 180, description: 'Fragrant basmati rice seasoned and tempered with crackled cumin seeds.' },
  { id: 'rice-9', name: 'CURD RICE', category: 'VEG RICE & NOODELS', price: 100, description: 'Traditional creamy cooling rice mixed with fresh yogurt and light spices.' },
  { id: 'rice-10', name: 'BABY CORN FRIED RICE', category: 'VEG RICE & NOODELS', price: 240, description: 'Delicate fried rice tossed with crunchy golden baby corn spears and scallions.' },
  { id: 'rice-11', name: 'SP BABY CORN FRIED RICE', category: 'VEG RICE & NOODELS', price: 280, description: 'Special crispy loaded baby corn fried rice tossed over hot high-flame wok strings.' },
  { id: 'rice-12', name: 'GOBI FRIED RICE', category: 'VEG RICE & NOODELS', price: 240, description: 'Flavorful stir-fried rice tossed with golden, crispy cauliflower florets.' },

  // 5. VEG CURRIES
  { id: 'curry-1', name: 'MIX VEG CURRY', category: 'VEG CURRIES', price: 180, description: 'Assorted seasonal fresh vegetables cooked together in an authentic mildly spiced gravy.' },
  { id: 'curry-2', name: 'ALU PALAK CURRY', category: 'VEG CURRIES', price: 180, description: 'Tender cubed potatoes simmered directly within a seasoned spinach puree.' },
  { id: 'curry-3', name: 'GREEN PEAS MASALA', category: 'VEG CURRIES', price: 100, description: 'Fresh sweet green peas cooked in an aromatic, spiced ginger-garlic curry.' },
  { id: 'curry-4', name: 'CAPSICUM MASALA', category: 'VEG CURRIES', price: 180, description: 'Crunchy diced green bell peppers cooked into a rich sesame masala base.' },
  { id: 'curry-5', name: 'METHI CHAMAN CURRY', category: 'VEG CURRIES', price: 250, description: 'Traditional specialty combining fresh fenugreek leaves and grated paneer.' },
  { id: 'curry-6', name: 'CASHEW TOMATO', category: 'VEG CURRIES', price: 240, description: 'Whole roasted premium cashew nuts slow-simmered inside a smooth, tangy tomato gravy.' },
  { id: 'curry-7', name: 'PANEER CURRY', category: 'VEG CURRIES', price: 200, description: 'Fresh, soft cottage cheese cubes cooked inside a simple and classic home-style sauce.' },
  { id: 'curry-8', name: 'KADAI PANEER CURRY', category: 'VEG CURRIES', price: 240, description: 'Paneer cubes and bell peppers wok-tossed with freshly ground spice layers.' },
  { id: 'curry-9', name: 'PANEER BUTTER MASALA', category: 'VEG CURRIES', price: 220, description: 'Premium soft cottage cheese chunks running inside a rich, silky makhani gravy.' },
  { id: 'curry-10', name: 'PALAK PANEER', category: 'VEG CURRIES', price: 250, description: 'Paneer inside a heavily seasoned fresh spinach cream puree.' },
  { id: 'curry-11', name: 'PALAK SHAHI KOFTA', category: 'VEG CURRIES', price: 250, description: 'Stuffed vegetable dumplings served deep within an exquisite spinach curry.' },
  { id: 'curry-12', name: 'PANEER CASHEW CURRY', category: 'VEG CURRIES', price: 250, description: 'An opulent gravy matching premium pan-roasted cashews with soft fresh paneer cubes.' },
  { id: 'curry-13', name: 'MUSHROOM CURRY', category: 'VEG CURRIES', price: 200, description: 'Freshly harvested sliced button mushrooms slow-cooked within a classic, clean gravy.' },
  { id: 'curry-14', name: 'MUSHROOM MASALA', category: 'VEG CURRIES', price: 220, description: 'Juicy button mushrooms sauteed over high heat and folded into a dense masala sauce.' },
  { id: 'curry-15', name: 'MUSHROOM CASHEW', category: 'VEG CURRIES', price: 250, description: 'Fresh mushrooms combined with toasted whole cashews inside a rich cream base.' },
  { id: 'curry-16', name: 'BABY CORN CURRY', category: 'VEG CURRIES', price: 200, description: 'Tender sweet baby corn wheels slow-cooked alongside garden herbs.' },
  { id: 'curry-17', name: 'BABY CORN MASALA', category: 'VEG CURRIES', price: 220, description: 'Crunchy baby corn rounds tossed directly within a spicy and tangy thick onion gravy.' },
  { id: 'curry-18', name: 'CASHEW FRY', category: 'VEG CURRIES', price: 240, description: 'Premium whole cashew nuts deep-fried in clear ghee and coated in pan-roasted dry spices.' },
  { id: 'curry-19', name: 'CASHEW MASALA', category: 'VEG CURRIES', price: 280, description: 'Full roasted cashew kernels simmered inside a highly spiced, velvety rich gravy.' },
  { id: 'curry-20', name: 'VEG JAIPUR CURRY', category: 'VEG CURRIES', price: 200, description: 'A vibrant medley cooked with crushed paneer, whole spices, and topped with crispy papad.' },
  { id: 'curry-21', name: 'VEG KUNDAN KUSH', category: 'VEG CURRIES', price: 240, description: 'Chef\'s secret signature recipe featuring stuffed baby vegetables in an exclusive rich sauce.' },
  { id: 'curry-22', name: 'MALAI KOFTA', category: 'VEG CURRIES', price: 280, description: 'Luxury paneer and potato dumplings served swimming inside an ultra-rich cream gravy.' },
  { id: 'curry-23', name: 'PANEER TIKKA MASALA', category: 'VEG CURRIES', price: 300, description: 'Clay-oven tandoor grilled smoky marinated paneer cooked into a spicy tikka gravy.' },
  { id: 'curry-24', name: 'PANEER KOFTA', category: 'VEG CURRIES', price: 250, description: 'Melt-in-mouth cottage cheese dumpling spheres deep fried and simmered within an aromatic curry.' },

  // 6. NON VEG SOUPS
  { id: 'nvsoup-1', name: 'CHICKEN SOUP', category: 'NON VEG SOUPS', price: 140, description: 'Warm and comforting classic clear chicken soup.' },
  { id: 'nvsoup-2', name: 'CHICKEN SWEET CORN SOUP', category: 'NON VEG SOUPS', price: 140, description: 'Creamy sweet corn soup packed with tender chicken bits.' },
  { id: 'nvsoup-3', name: 'CHICKEN DRAGON SOUP', category: 'NON VEG SOUPS', price: 150, description: 'Fiery and flavorful red Chinese soup with chicken.' },
  { id: 'nvsoup-4', name: 'CHICKEN CLEAR SOUP', category: 'NON VEG SOUPS', price: 140, description: 'Light, nutrient-rich broth simmered with fresh herbs.' },
  { id: 'nvsoup-5', name: 'LEMON CORIANDER SOUP', category: 'NON VEG SOUPS', price: 140, description: 'Tangy lemon and fresh coriander soup base with chicken.' },
  { id: 'nvsoup-6', name: 'MUTTON BONE SOUP', category: 'NON VEG SOUPS', price: 160, description: 'Traditional slow-cooked bone broth rich in spices.' },

  // 7. NON VEG RICE & NOODELS
  { id: 'nvrice-1', name: 'EGG FRIED RICE', category: 'NON VEG RICE & NOODELS', price: 200, description: 'Wok-tossed basmati rice with scrambled egg bits.' },
  { id: 'nvrice-2', name: 'CHICKEN FRIED RICE', category: 'NON VEG RICE & NOODELS', price: 250, description: 'Classic stir-fried rice tossed with tender chicken chunks.' },
  { id: 'nvrice-3', name: 'SP CHICKEN FRIED RICE', category: 'NON VEG RICE & NOODELS', price: 330, description: 'Chef special premium loaded fried rice with double chicken.' },
  { id: 'nvrice-4', name: 'SCHEZWAN CHICKEN FRIED RICE', category: 'NON VEG RICE & NOODELS', price: 300, description: 'Fiery wok-fried rice tossed in a hot Schezwan chili paste.' },
  { id: 'nvrice-5', name: 'CHICKEN 65 FRIED RICE', category: 'NON VEG RICE & NOODELS', price: 350, description: 'Indo-Chinese fusion rice mixed with crispy Chicken 65 pieces.' },
  { id: 'nvrice-6', name: 'CHICKEN FRY PIECE FRIED RICE', category: 'NON VEG RICE & NOODELS', price: 280, description: 'Aromatic fried rice topped with crispy golden pan-fried chicken.' },
  { id: 'nvrice-7', name: 'MUTTON FRIED RICE', category: 'NON VEG RICE & NOODELS', price: 300, description: 'Richly seasoned basmati rice tossed with tender mutton shreds.' },
  { id: 'nvrice-8', name: 'SP MUTTON FRIED RICE', category: 'NON VEG RICE & NOODELS', price: 350, description: 'Elevated premium mutton fried rice with extra meat chunks.' },
  { id: 'nvrice-9', name: 'MIX FRIED RICE', category: 'NON VEG RICE & NOODELS', price: 300, description: 'Loaded fried rice combining chicken, mutton pieces, and egg.' },
  { id: 'nvrice-10', name: 'PRAWNS FRIED RICE', category: 'NON VEG RICE & NOODELS', price: 300, description: 'Delicious stir-fried rice tossed with plump shrimp.' },
  { id: 'nvrice-11', name: 'SP PRAWNS FRIED RICE', category: 'NON LOG RICE & NOODELS', price: 350, description: 'Specialty loaded shrimp fried rice tossed over high flame.' },
  { id: 'nvrice-12', name: 'MUGHLAI FRIED RICE', category: 'NON VEG RICE & NOODELS', price: 280, description: 'Rich specialty mild fried rice recipe prepared in egg coatings.' },
  { id: 'nvrice-13', name: 'EGG SOFT NOODLES', category: 'NON VEG RICE & NOODELS', price: 150, description: 'Wok-shredded long noodles stir-fried with farm eggs.' },

  // 8. NON VEG STARTERS
  { id: 'nvstart-1', name: 'CHICKEN DRY ROAST (BONE)', category: 'NON VEG STARTERS', price: 230, description: 'Spicy pan-roasted bone chicken pieces.' },
  { id: 'nvstart-2', name: 'CHICKEN DRY ROAST (BONELESS)', category: 'NON VEG STARTERS', price: 280, description: 'Succulent boneless chicken pieces dry roasted with black pepper.' },
  { id: 'nvstart-3', name: 'CHICKEN FRY BONE', category: 'NON VEG STARTERS', price: 220, description: 'Deep-fried bone chicken marinated in spices.' },
  { id: 'nvstart-4', name: 'CHICKEN FRY BONELESS', category: 'NON VEG STARTERS', price: 260, description: 'Golden crispy fried boneless chicken pieces.' },
  { id: 'nvstart-5', name: 'CHILLY CHICKEN', category: 'NON VEG STARTERS', price: 250, description: 'Classic Indo-Chinese wok-tossed hot chili chicken.' },
  { id: 'nvstart-6', name: 'CHICKEN MANCHURIA', category: 'NON VEG STARTERS', price: 250, description: 'Popular crispy fried chicken chunks in a tangy Manchurian glaze.' },
  { id: 'nvstart-7', name: 'CHICKEN 65', category: 'NON VEG STARTERS', price: 250, description: 'Fiery deep-fried southern Indian classic spiced chicken appetizer.' },
  { id: 'nvstart-8', name: 'PEPPER CHICKEN', category: 'NON VEG STARTERS', price: 280, description: 'Wok-tossed chicken seasoned heavily with freshly crushed peppercorns.' },
  { id: 'nvstart-9', name: 'CHICKEN 555', category: 'NON VEG STARTERS', price: 280, description: 'Chef special stripped chicken tossed with cashew nuts and sweet-spicy strings.' },
  { id: 'nvstart-10', name: 'CHICKEN WINGLETS', category: 'NON VEG STARTERS', price: 280, description: 'Crispy marinated delicious chicken wings fried to perfection.' },
  { id: 'nvstart-11', name: 'CHICKEN DRUM STICKS', category: 'NON VEG STARTERS', price: 350, description: 'Spicy seasoned full chicken legs cooked tender.' },
  { id: 'nvstart-12', name: 'CHICKEN LOLLY POP', category: 'NON VEG STARTERS', price: 350, description: 'All-time favorite fun winglet lollipops inside thick crimson glaze layers.' },
  { id: 'nvstart-13', name: 'GARLIC CHICKEN', category: 'NON VEG STARTERS', price: 350, description: 'Stir-fried chicken loaded with minced pungent garlic flakes and light soy.' },
  { id: 'nvstart-14', name: 'CHICKEN JOINT ROAST', category: 'NON VEG STARTERS', price: 260, description: 'Premium whole leg joint slow roasted in hand-pounded masalas.' },
  { id: 'nvstart-15', name: 'CHICKEN JOINT ROAST (SEMI GRAVY)', category: 'NON VEG STARTERS', price: 150, description: 'Juicy chicken roast joint sitting inside a thick spicy sauce layer.' },
  { id: 'nvstart-16', name: 'CHICKEN DUM PIECES', category: 'NON VEG STARTERS', price: 170, description: 'Slow slow-cooked dum style spiced chicken portions.' },
  { id: 'nvstart-17', name: 'CHICKEN DRAGON', category: 'NON VEG STARTERS', price: 150, description: 'Stripped batter-fried chicken glazed in a fiery dragon chili reduction.' },
  { id: 'nvstart-18', name: 'CHICKEN HONGKONG', category: 'NON VEG STARTERS', price: 280, description: 'Sweet and spicy wok-fried chicken accented with dark sauce profiles.' },
  { id: 'nvstart-19', name: 'LEMON CHICKEN', category: 'NON VEG STARTERS', price: 260, description: 'Tangy and aromatic pan-fried chicken tossed with fresh citrus lemon rinds.' },
  { id: 'nvstart-20', name: 'SLICE CHILLY CHICKEN', category: 'NON VEG STARTERS', price: 280, description: 'Thinly sliced chicken wok-fried crisp alongside green chilis.' },
  { id: 'nvstart-21', name: 'CHICKEN BBQ', category: 'NON VEG STARTERS', price: 280, description: 'Smoky grilled chicken pieces coated in rich barbecue layout arrays.' },
  { id: 'nvstart-22', name: 'CHICKEN GULKARA', category: 'NON VEG STARTERS', price: 280, description: 'Specialty aromatic house recipe featuring complex spice profiles.' },
  { id: 'nvstart-23', name: 'CASHEW CHICKEN DRY', category: 'NON VEG STARTERS', price: 350, description: 'Rich appetizer tossing chicken chunks with plenty of whole cashews.' },
  { id: 'nvstart-24', name: 'CHICKEN MAJESTIC', category: 'NON VEG STARTERS', price: 300, description: 'Fried chicken strips glazed elegantly in a smooth yogurt-mint coating.' },
  { id: 'nvstart-25', name: 'CHICKEN SATYA', category: 'NON VEG STARTERS', price: 300, description: 'Exotic charcoal skewered spice marinated operational starter items.' },
  { id: 'nvstart-26', name: 'CHICKEN KEEMA BALLS', category: 'NON VEG STARTERS', price: 280, description: 'Crispy fried spherical bites made from minced seasoned chicken.' },
  { id: 'nvstart-27', name: 'CHICKEN LIVER FRY', category: 'NON VEG STARTERS', price: 350, description: 'Rich chicken liver pieces pan fried crisp with cracked black pepper.' },
  { id: 'nvstart-28', name: 'CHICKEN KHATIYA ROLL', category: 'NON VEG STARTERS', price: 300, description: 'Savory layered flatbread roll stuffed with spicy hot chicken pieces.' },
  { id: 'nvstart-29', name: 'CHICKEN GHEE ROAST', category: 'NON VEG STARTERS', price: 250, description: 'Aromatic Kundapur style chicken roasted slow in premium pure ghee.' },
  { id: 'nvstart-30', name: 'MUTTON GHEE ROAST', category: 'NON VEG STARTERS', price: 250, description: 'Tender mutton pieces slow cooked and roasted in rich, clear ghee layouts.' },
  { id: 'nvstart-31', name: 'MUTTON FRY', category: 'NON VEG STARTERS', price: 300, description: 'Classic country-style pan-fried mutton chucks loaded with black pepper.' },
  { id: 'mutton-32', name: 'MUTTON MANCHURIA', category: 'NON VEG STARTERS', price: 350, description: 'Indo-Chinese style crispy fried mutton blocks tossed in soy sauce glaze.' },
  { id: 'nvstart-33', name: 'CHILLY MUTTON', category: 'NON VEG STARTERS', price: 300, description: 'Wok-seared tender mutton pieces running with onions and hot green chilis.' },
  { id: 'nvstart-34', name: 'GINGER MUTTON', category: 'NON VEG STARTERS', price: 350, description: 'Savory mutton starter driven heavily by fresh julienned ginger roots.' },
  { id: 'nvstart-35', name: 'MUTTON MILLENNIUM', category: 'NON VEG STARTERS', price: 350, description: 'Exclusive special recipe layered with rich premium nut reductions.' },
  { id: 'nvstart-36', name: 'PRAWNS FRY', category: 'NON VEG STARTERS', price: 350, description: 'Delicious pan-fried prawns seasoned with regional spice mixes.' },
  { id: 'nvstart-37', name: 'LOOSE PRAWNS', category: 'NON VEG STARTERS', price: 400, description: 'Crispy butter-fried prawns dusted in dry salt and chili flakes.' },
  { id: 'nvstart-38', name: 'CHILLY PRAWNS', category: 'NON VEG STARTERS', price: 280, description: 'Wok tossed crisp prawns with peppers and dark fiery chili soy.' },
  { id: 'nvstart-39', name: 'GINGER PRAWNS', category: 'NON VEG STARTERS', price: 300, description: 'Tender shrimp cooked slow with thick ginger pastes and scallions.' },
  { id: 'nvstart-40', name: 'PRAWNS MANCHURIA', category: 'NON VEG STARTERS', price: 300, description: 'Golden fried prawns tossed directly inside rich garlic Manchurian bases.' },
  { id: 'nvstart-41', name: 'APOLLO FISH', category: 'NON VEG STARTERS', price: 300, description: 'Hyderabadi style cubes of fish fried and tossed in yogurt curry-leaf mix.' },
  { id: 'nvstart-42', name: 'CHILLY FISH (BONELESS)', category: 'NON VEG STARTERS', price: 300, description: 'Boneless fish fillets wok-seared with premium green chilis.' },
  { id: 'nvstart-43', name: 'FISH FRY (BONE)', category: 'NON VEG STARTERS', price: 300, description: 'Traditional bone-in fish steaks tawa-fried till completely crispy.' },
  { id: 'nvstart-44', name: 'FISH ROAST', category: 'NON VEG STARTERS', price: 180, description: 'Spiced fish fillets slow roasted over low heat plate strings.' },
  { id: 'nvstart-45', name: 'BUTTER PRAWNS', category: 'NON VEG STARTERS', price: 180, description: 'Creamy sweet prawns running inside garlic butter gloss layers.' },
  { id: 'nvstart-46', name: 'D.G. FRY', category: 'NON VEG STARTERS', price: 300, description: 'House special crispy seafood item seasoned with choice masalas.' },
  { id: 'nvstart-47', name: 'OMLET', category: 'NON VEG STARTERS', price: 350, description: 'Double egg fluffy pan omelette.' },

  // 9. NON VEG BRIYANI
  { id: 'nvbiryani-1', name: 'EMPTY BIRYANI', category: 'NON VEG BRIYANI', price: 160, description: 'Fragrant, highly seasoned basmati rice served completely plain.' },
  { id: 'nvbiryani-2', name: 'HYD CHICKEN DUM BIRYANI', category: 'NON VEG BRIYANI', price: 280, description: 'Authentic rich Hyderabadi spice layered chicken cooked slow under dum.' },
  { id: 'nvbiryani-3', name: 'HALF - CHICKEN BIRYANI', category: 'NON VEG BRIYANI', price: 200, description: 'Satisfying smaller portion size layout of our special chicken biryani.' },
  { id: 'nvbiryani-4', name: 'CHICKEN FRY BIT BIRYANI', category: 'NON VEG BRIYANI', price: 280, description: 'Basmati rice served alongside crispy, deep-fried chicken bone bits.' },
  { id: 'nvbiryani-5', name: 'HALF - CHICKEN FRY BIT BIRYANI', category: 'NON VEG BRIYANI', price: 200, description: 'Half plate tier portion matching flavorful rice with crispy fried chicken.' },
  { id: 'nvbiryani-6', name: 'CHICKEN MUGHLAI BIRYANI', category: 'NON VEG BRIYANI', price: 300, description: 'Rich, specialty rice topped with egg ribbons and rich cashew chicken gravies.' },
  { id: 'nvbiryani-7', name: 'HALF - CHICKEN MUGHLAI BIRYANI', category: 'NON VEG BRIYANI', price: 220, description: 'Lighter plate segment sizing down our egg-layered chicken variant.' },
  { id: 'nvbiryani-8', name: 'MUTTON FRY BIT BIRYANI', category: 'NON VEG BRIYANI', price: 330, description: 'Aromatic biryani rice served packed with pan-seared crispy small mutton bits.' },
  { id: 'nvbiryani-9', name: 'HALF - MUTTON FRY BIT BIRYANI', category: 'NON VEG BRIYANI', price: 230, description: 'Portion calibrated half layout containing crunchy fried mutton bits.' },
  { id: 'nvbiryani-10', name: 'SP MUTTON BIRYANI', category: 'NON VEG BRIYANI', price: 350, description: 'Chef special rich recipe cooked with selected tender cuts and saffron.' },
  { id: 'nvbiryani-11', name: 'MUTTON DUM BIRYANI', category: 'NON VEG BRIYANI', price: 350, description: 'Traditional recipe slow slow-cooking long grain rice with spiced raw mutton chunks.' },
  { id: 'nvbiryani-12', name: 'HALF - MUTTON DUM BIRYANI', category: 'NON VEG BRIYANI', price: 250, description: 'Tender half plate configuration of our slow-steamed bone mutton specialty.' },
  { id: 'nvbiryani-13', name: 'MUTTON KEEMA BIRYANI', category: 'NON VEG BRIYANI', price: 400, description: 'Fluffy basmati long grains cooked layered with spiced minced mutton.' },
  { id: 'nvbiryani-14', name: 'PRAWNS BIRYANI', category: 'NON VEG BRIYANI', price: 350, description: 'Flavorful spiced rice prepared layered with freshly sourced butter-fried shrimp.' },
  { id: 'nvbiryani-15', name: 'HALF - PRAWNS BIRYANI', category: 'NON VEG BRIYANI', price: 230, description: 'Half plate portion segment housing seasoned small spiced prawns.' },
  { id: 'nvbiryani-16', name: 'SP CHICKEN BIRYANI', category: 'NON VEG BRIYANI', price: 350, description: 'Special signature tier chicken biryani using premium basmati profiles.' },
  { id: 'nvbiryani-17', name: 'MIX BIRYANI', category: 'NON VEG BRIYANI', price: 330, description: 'Ultimate combination platter rice plate including chicken, mutton, and shrimp.' },
  { id: 'nvbiryani-18', name: 'HALF - MIX BIRYANI', category: 'NON VEG BRIYANI', price: 230, description: 'Calibrated smaller multi-meat combination plate for solo diners.' },
  { id: 'nvbiryani-19', name: 'HARSHA SP PRAWNS BIRYANI', category: 'NON VEG BRIYANI', price: 380, description: 'Exclusive house specialty loaded with giant jumbo-fried prawns.' },
  { id: 'nvbiryani-20', name: 'HARSHA SP CHICKEN BIRYANI', category: 'NON VEG BRIYANI', price: 350, description: 'Top-tier master recipe loaded with rich shredded chicken masalas.' },
  { id: 'nvbiryani-21', name: 'CHICKEN DRAGON BIRYANI', category: 'NON VEG BRIYANI', price: 380, description: 'Fiery hot fusion mixing dragon style red glaze chicken pieces with biryani rice.' },
  { id: 'nvbiryani-22', name: 'EGG BIRYANI', category: 'NON VEG BRIYANI', price: 180, description: 'Savory long grain biryani rice cooked combined with spiced boiled eggs.' },
  { id: 'nvbiryani-23', name: 'HARSHA FAMILY PACK', category: 'NON VEG BRIYANI', price: 650, description: 'Mega portion pack complete with massive multi-meat allocations and eggs.' },
  { id: 'nvbiryani-24', name: 'KABAB BIRYANI', category: 'NON VEG BRIYANI', price: 400, description: 'Aromatic basmati layers crowned cleanly with chicken seekh kababs.' },
  { id: 'nvbiryani-25', name: 'TANDOORI BIRYANI', category: 'NON VEG BRIYANI', price: 450, description: 'Long grain rice paired with clay-oven roasted hot tandoori chicken.' },
  { id: 'nvbiryani-26', name: 'CHICKEN TIKKA BIRYANI', category: 'NON VEG BRIYANI', price: 400, description: 'Smoky grilled red boneless chicken chunks layered inside spiced orange rice.' },
  { id: 'nvbiryani-27', name: 'DILKUSH BIRYANI', category: 'NON VEG BRIYANI', price: 400, description: 'Rich specialty item baked layered with extremely smooth premium nut arrays.' },
  { id: 'nvbiryani-28', name: 'ROSE BIRYANI', category: 'NON VEG BRIYANI', price: 380, description: 'Fragrant unique premium basmati profile infused with rose distillates.' },
  { id: 'nvbiryani-29', name: 'RAJULU BIRYANI', category: 'NON VEG BRIYANI', price: 380, description: 'Traditional royal spicy formula utilizing high-heat green chilis.' },
  { id: 'nvbiryani-30', name: 'POTLAM BIRYANI', category: 'NON VEG BRIYANI', price: 400, description: 'Famous item packing a loaded biryani safe inside an ultra-thin pan omelette pocket.' },
  { id: 'nvbiryani-31', name: 'PRAWNS MUGHLAI BIRYANI', category: 'NON VEG BRIYANI', price: 380, description: 'Luxury shrimp rice variant prepared running with egg drops and cashews.' },
  { id: 'nvbiryani-32', name: 'MUTTON MUGHLAI BIRYANI', category: 'NON VEG BRIYANI', price: 400, description: 'Tender mutton strips glazed into egg-creams and folded inside basmati rice.' },
  { id: 'nvbiryani-33', name: 'MIXED MUGHLAI BIRYANI', category: 'NON VEG BRIYANI', price: 380, description: 'Opulent multi-meat dynamic blend structured inside egg makhani gravies.' },
  { id: 'nvbiryani-34', name: 'CHICKEN JOINT BIRYANI', category: 'NON VEG BRIYANI', price: 350, description: 'Fragrant long grains served paired with whole leg joint cuts.' },
  { id: 'nvbiryani-35', name: 'SPECIAL BIRYANI', category: 'NON VEG BRIYANI', price: 350, description: 'Chef special premium recipe showcasing rich variations of our meat inventory.' },

  // 10. NON VEG CURRIES
  { id: 'nvcurry-1', name: 'AP SPECIAL CHICKEN CURRY', category: 'NON VEG CURRIES', price: 280, description: 'Spicy house special chicken gravy.' },
  { id: 'nvcurry-2', name: 'BUTTER CHICKEN CURRY', category: 'NON VEG CURRIES', price: 280, description: 'Tender chicken chunks cooked in a rich, velvety butter makhani sauce.' },
  { id: 'nvcurry-3', name: 'KADAI CHICKEN CURRY', category: 'NON VEG CURRIES', price: 280, description: 'Wok-tossed chicken with capsicum and Kadai spices.' },
  { id: 'nvcurry-4', name: 'CHICKEN CURRY (BONE)', category: 'NON VEG CURRIES', price: 230, description: 'Traditional bone-in chicken pieces slow cooked in a savory gravy.' },
  { id: 'nvcurry-5', name: 'CHICKEN CURRY (BONELESS)', category: 'NON VEG CURRIES', price: 280, description: 'Succulent boneless chicken pieces simmered inside a classic gravy.' },
  { id: 'nvcurry-6', name: 'CHICKEN TIKKA MASALA CURRY', category: 'NON VEG CURRIES', price: 300, description: 'Smoky tandoor-grilled chicken tikka cubes folded into a spicy gravy.' },
  { id: 'nvcurry-7', name: 'CHICKEN MUGHLAI CURRY', category: 'NON VEG CURRIES', price: 300, description: 'Rich royal gravy layered with egg cascades and cashew pastes.' },
  { id: 'nvcurry-8', name: 'CHICKEN MAHARANI CURRY', category: 'NON VEG CURRIES', price: 300, description: 'Mild and opulent creamy chicken curry flavored with saffron.' },
  { id: 'nvcurry-9', name: 'METHI CHICKEN CURRY', category: 'NON VEG CURRIES', price: 300, description: 'Aromatic chicken curry enriched with fenugreek leaves.' },
  { id: 'nvcurry-10', name: 'MUTTON CURRY', category: 'NON VEG CURRIES', price: 280, description: 'Classic slow-cooked tender mutton pieces in a robust gravy.' },
  { id: 'nvcurry-11', name: 'AP SPECIAL MUTTON CURRY', category: 'NON VEG CURRIES', price: 300, description: 'Signature hot fiery Andhra style mutton curry.' },
  { id: 'nvcurry-12', name: 'MUTTON GONGURA', category: 'NON VEG CURRIES', price: 300, description: 'Tender mutton cooked with tangy sorrel leaves.' },
  { id: 'nvcurry-13', name: 'MUTTON MAGO', category: 'NON VEG CURRIES', price: 300, description: 'Chef special aromatic mutton preparation.' },
  { id: 'nvcurry-14', name: 'MUTTON KEEMA CURRY', category: 'NON VEG CURRIES', price: 350, description: 'Finely minced mutton cooked with hand-pounded masalas.' },
  { id: 'nvcurry-15', name: 'MUTTON CASHEW CURRY', category: 'NON VEG CURRIES', price: 350, description: 'Opulent mutton gravy mixed with toasted whole cashews.' },
  { id: 'nvcurry-16', name: 'MUTTON NALLI CURRY', category: 'NON VEG CURRIES', price: 300, description: 'Exclusive recipe utilizing slow-cooked mutton shanks.' },
  { id: 'nvcurry-17', name: 'PRAWNS CURRY', category: 'NON VEG CURRIES', price: 280, description: 'Delicious pan-cooked prawns simmered inside a mild home-style gravy.' },
  { id: 'nvcurry-18', name: 'PRAWNS MASALA', category: 'NON VEG CURRIES', price: 300, description: 'Plump shrimp pan-seared and folded into a thick masala.' },
  { id: 'nvcurry-19', name: 'BUTTER PRAWNS CURRY', category: 'NON VEG CURRIES', price: 280, description: 'Rich and creamy shrimp dish prepared within a butter makhani glaze.' },
  { id: 'nvcurry-20', name: 'CHICKEN BONE MASALA', category: 'NON VEG CURRIES', price: 280, description: 'Thick semi-dry chicken recipe focusing on deeply caramelized aromatics.' },
  { id: 'nvcurry-21', name: 'D.G. CURRY', category: 'NON VEG CURRIES', price: 300, description: 'House specialty master non-veg preparation.' },
  { id: 'nvcurry-22', name: 'EGG CURRY', category: 'NON VEG CURRIES', price: 150, description: 'Hard-boiled pan-seared egg halves served inside a golden onion curry.' },
  { id: 'nvcurry-23', name: 'FISH CURRY', category: 'NON VEG CURRIES', price: 180, description: 'Traditional coastal fish curry cooked with tangy tamarind.' },
  { id: 'nvcurry-24', name: 'FISH MASALA', category: 'NON VEG CURRIES', price: 180, description: 'Tawa fish fillets seared inside a deep pepper and garlic reduction.' },
  { id: 'nvcurry-25', name: 'FISH PULUSU', category: 'NON VEG CURRIES', price: 180, description: 'Authentic local Andhra style spicy-sour fish stew.' },

  // 11. NAANS & ROTI
  { id: 'bread-1', name: 'TANDOORI ROTI', category: 'NAANS & ROTI', price: 40, description: 'Traditional whole wheat flatbread baked fresh in our clay oven.' },
  { id: 'bread-2', name: 'BUTTER ROTI', category: 'NAANS & ROTI', price: 60, description: 'Freshly baked whole wheat tandoori roti generously coated in rich butter.' },
  { id: 'bread-3', name: 'PLAIN NAAN', category: 'NAANS & ROTI', price: 0, description: 'Classic soft and fluffy leavened flatbread.' },
  { id: 'bread-4', name: 'BUTTER NAAN', category: 'NAANS & ROTI', price: 0, description: 'Leavened flatbread layered with premium melted butter.' },
  { id: 'bread-5', name: 'MUGHLAI NAAN', category: 'NAANS & ROTI', price: 0, description: 'Rich leavened soft naan bread filled in traditional style.' },
  { id: 'bread-6', name: 'GARLIC NAAN', category: 'NAANS & ROTI', price: 0, description: 'Fluffy tandoor-baked naan bread layered with aromatic garlic flakes.' },
  { id: 'bread-7', name: 'PUDINA PAROTTA', category: 'NAANS & ROTI', price: 0, description: 'Multi-layered flaky flatbread flavored with crushed mint leaves.' },
  { id: 'bread-8', name: 'ALU PAROTTA', category: 'NAANS & ROTI', price: 0, description: 'Flaky multi-layered parotta stuffed with a savory potato filling.' },

  // 12. TANDURI & KABA'S (Newly Added from image_863264.png)
  { id: 'tandoor-1', name: 'PANEER TIKKA', category: 'TANDURI & KABA\'S', price: 300, description: 'Spiced cottage cheese cubes skewered with vegetables and grilled in the tandoor.' },
  { id: 'tandoor-2', name: 'PANEER MALAI TIKKA', category: 'TANDURI & KABA\'S', price: 300, description: 'Creamy marinated cottage cheese chunks grilled to a delicate perfection.' },
  { id: 'tandoor-3', name: 'KANDHARI KABAB', category: 'TANDURI & KABA\'S', price: 300, description: 'Richly spiced chicken kababs infused with pomegranate zest and regional herbs.' },
  { id: 'tandoor-4', name: 'CHICKEN TIKKA', category: 'TANDURI & KABA\'S', price: 300, description: 'Classic boneless chicken cubes marinated in yogurt and spices, clay-oven grilled.' },
  { id: 'tandoor-5', name: 'FISH TIKKA', category: 'TANDURI & KABA\'S', price: 300, description: 'Tender chunks of boneless fish delicately spiced and tandoor-roasted.' },
  { id: 'tandoor-6', name: 'TANDOORI CHICKEN', category: 'TANDURI & KABA\'S', price: 550, description: 'Full chicken marinated in a robust yogurt-spice blend and roasted over charcoal.' },
  { id: 'tandoor-7', name: 'HALF TANDOORI CHICKEN', category: 'TANDURI & KABA\'S', price: 300, description: 'Half portion of our signature charcoal-roasted spicy tandoori chicken.' },
  { id: 'tandoor-8', name: 'TANDOORI KABAB', category: 'TANDURI & KABA\'S', price: 300, description: 'Succulent skewered chicken meat heavily spiced and flame-grilled.' },
  { id: 'tandoor-9', name: 'HALF TANDOORI KABAB', category: 'TANDURI & KABA\'S', price: 150, description: 'Smaller порция serving of our traditional spicy tandoori skewered kababs.' },
  { id: 'tandoor-10', name: 'KALMI KABAB', category: 'TANDURI & KABA\'S', price: 300, description: 'Premium chicken drumsticks coated in a rich, cashew-cream egg marinade and grilled.' },

  // 13. ONLY TABLE PURPOSE (Newly Added from image_863264.png)
  { id: 'table-1', name: 'HALF TOMATO SOUP', category: 'ONLY TABLE PURPOSE', price: 70, description: 'Half-portion size of our freshly prepared house tomato soup.' },
  { id: 'table-2', name: 'HALF SWEET CORN SOUP', category: 'ONLY TABLE PURPOSE', price: 70, description: 'Smaller portional size of our classic sweet corn soup base.' },
  { id: 'table-3', name: 'HALF VEG HOT & SOUR SOUP', category: 'ONLY TABLE PURPOSE', price: 70, description: 'Half-sized bowl of spicy and sour mixed vegetable soup broth.' },
  { id: 'table-4', name: 'HALF CHICKEN SWEET CORN SOUP', category: 'ONLY TABLE PURPOSE', price: 80, description: 'Comforting half portion of chicken sweet corn broth.' },
  { id: 'table-5', name: 'HALF CHICKEN CORN SOUP', category: 'ONLY TABLE PURPOSE', price: 80, description: 'Lighter serving size tracking our house chicken and corn recipe.' },
  { id: 'table-6', name: 'HALF CHICKEN HOT & SOUR SOUP', category: 'ONLY TABLE PURPOSE', price: 90, description: 'Fiery half portion bowl running chicken fragments and chilis.' },
  { id: 'table-7', name: 'CHICKEN FRIED WINGS', category: 'ONLY TABLE PURPOSE', price: 350, description: 'Golden crispy batter-fried chicken wings served table-side.' },

  // 14. DRINKS (Newly Added from image_863264.png)
  { id: 'drink-1', name: 'COOL DRINK', category: 'DRINKS', price: 30, description: 'Chilled soft drink selection.' },
  { id: 'drink-2', name: 'MINERAL WATER', category: 'DRINKS', price: 30, description: 'Packaged clean premium drinking water bottle.' },
  { id: 'drink-3', name: 'BUTTER MILK', category: 'DRINKS', price: 50, description: 'Traditional churning yogurt drink with crushed ginger, chilis, and coriander leaves.' },
  { id: 'drink-4', name: 'SWEET LASSI', category: 'DRINKS', price: 60, description: 'Thick, creamy churned sweet sweet yogurt beverage.' },
  { id: 'drink-5', name: 'LASSI SALT', category: 'DRINKS', price: 50, description: 'Refreshing salted churned yogurt recipe flavored with cumin.' },
  { id: 'drink-6', name: 'HALF LT COOL DRINK', category: 'DRINKS', price: 50, description: 'Chilled 500ml medium-sized soft drink bottle.' },
  { id: 'drink-7', name: 'COKE TINS', category: 'DRINKS', price: 50, description: 'Standard chilled Coca-Cola aluminum beverage can.' }
];